#!/bin/bash

# Deploy to AWS Amplify Hosting Script

echo "🚀 AWS Amplify Hosting Setup"
echo "============================"
echo ""
echo "Since Amplify Gen2 requires GitHub integration through the AWS Console,"
echo "please follow these steps:"
echo ""
echo "1. Open AWS Amplify Console:"
echo "   👉 https://console.aws.amazon.com/amplify/"
echo ""
echo "2. Click 'Create new app' → 'Host web app'"
echo ""
echo "3. Connect your GitHub repository:"
echo "   - Authorize AWS Amplify to access GitHub (if prompted)"
echo "   - Select your repository: salesforce-fullstack"
echo "   - Select branch: main"
echo ""
echo "4. Build settings will auto-detect from amplify.yml"
echo "   - Verify the build settings look correct"
echo "   - Click 'Next'"
echo ""
echo "5. Review and click 'Save and deploy'"
echo ""
echo "6. Wait for deployment to complete (5-10 minutes)"
echo ""
echo "7. Once deployed, you'll get a URL like:"
echo "   https://main.xxxxxx.amplifyapp.com"
echo ""
echo "📝 Important: After first deployment"
echo "   - Go to 'Backend environments' tab"
echo "   - Link your existing Amplify backend"
echo "   - This ensures your Cognito User Pool is connected"
echo ""
echo "📚 For detailed instructions, see: DEPLOYMENT_GUIDE.md"
echo ""
echo "Need help? Check the deployment guide:"
echo "   cat DEPLOYMENT_GUIDE.md"

